spring:
  application:
    name: test_utilModel
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/test_db
    username: jjg_test
    password: jjg_test1111
  session:
    store-type: jdbc
  sql:
    init:
      mode: always

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# MyBatis Mapper 위치 등록
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.utilmodel.VO

server:
  port: 8030